/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// PreemptionConfigPreemptionCandidateSelectorApplyConfiguration represents a declarative configuration of the PreemptionConfigPreemptionCandidateSelector type for use
// with apply.
//
// PreemptionConfigPreemptionCandidateSelector defines the selection criteria for workloads that are candidates for preemption.
type PreemptionConfigPreemptionCandidateSelectorApplyConfiguration struct {
	// scope specifies the queue or cohort relation boundary of candidates to the preemptor workload.
	Scope *kueuev1beta2.PreemptionConfigPreemptionQueueScope `json:"scope,omitempty"`
	// numericLabels defines rules for filtering candidates using custom numeric labels on the Workload resource.
	// Multiple numeric labels are joined using AND-rule (all have to be satisfied).
	// Accepts all if not set.
	NumericLabels []PreemptionConfigNumericLabelConstraintApplyConfiguration `json:"numericLabels,omitempty"`
	// relativeWorkloadPriority defines how the candidate's priority compares to the preemptor's priority.
	// For example "LessThan" means that only workloads with lower priority will be allowed as preemption candidates.
	// The comparison is made using effective priority (accounting for priority boost if enabled).
	// If nil, no relative priority check is enforced.
	//
	// TODO(#13396): replace with the `priority` field of the KEP
	// (PreemptionConfigPriorityConstraint, carrying an explicit Base/Boosted mode) once the
	// priority boost semantics are settled.
	RelativeWorkloadPriority *kueuev1beta2.NumericComparison `json:"relativeWorkloadPriority,omitempty"`
}

// PreemptionConfigPreemptionCandidateSelectorApplyConfiguration constructs a declarative configuration of the PreemptionConfigPreemptionCandidateSelector type for use with
// apply.
func PreemptionConfigPreemptionCandidateSelector() *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration {
	return &PreemptionConfigPreemptionCandidateSelectorApplyConfiguration{}
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration) WithScope(value kueuev1beta2.PreemptionConfigPreemptionQueueScope) *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration {
	b.Scope = &value
	return b
}

// WithNumericLabels adds the given value to the NumericLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NumericLabels field.
func (b *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration) WithNumericLabels(values ...*PreemptionConfigNumericLabelConstraintApplyConfiguration) *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNumericLabels")
		}
		b.NumericLabels = append(b.NumericLabels, *values[i])
	}
	return b
}

// WithRelativeWorkloadPriority sets the RelativeWorkloadPriority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RelativeWorkloadPriority field is set to the value of the last call.
func (b *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration) WithRelativeWorkloadPriority(value kueuev1beta2.NumericComparison) *PreemptionConfigPreemptionCandidateSelectorApplyConfiguration {
	b.RelativeWorkloadPriority = &value
	return b
}
