apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kueue-system

resources:
  - ../components/crd
  - ../components/manager
  - ../components/visibility

components:
  - ../components/visibility-server

labels:
  - pairs:
      app: visibility-on-demand
    includeSelectors: true
    includeTemplates: true

patches:
  - target:
      kind: Namespace
      name: system
    patch: |-
      - op: replace
        path: /metadata/name
        value: kueue-system
  - path: manager_config_patch.yaml
  - path: manager_visibility_patch.yaml
  - target:
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: replace
        path: /metadata/name
        value: visibility-on-demand
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: ["/visibility-on-demand"]
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue:v0.18.0-devel-176-g705b94298-dirty
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
